--Example of a job step using SYSTEM_DATBASES - FULL as the example, change lines 125 and 126 to what you need to add this as the job step instead of what is currently there
DECLARE @Databases nvarchar(max),
	@Directory nvarchar(max),
	@BackupType nvarchar(max),
	@Verify nvarchar(max),
	@CleanupTime int,
	@CleanupMode nvarchar(max),
	@Compress nvarchar(max),
	@CopyOnly nvarchar(max),
	@ChangeBackupType nvarchar(max),
	@BackupSoftware nvarchar(max),
	@CheckSum nvarchar(max),
	@BlockSize int,
	@BufferCount int,
	@MaxTransferSize int,
	@NumberOfFiles int,
	@MinBackupSizeForMultipleFiles int,
	@MaxFileSize int,
	@CompressionLevel int,
	@Description nvarchar(max),
	@Threads int,
	@Throttle int,
	@Encrypt nvarchar(max),
	@EncryptionAlgorithm nvarchar(max),
	@ServerCertificate nvarchar(max),
	@ServerAsymmetricKey nvarchar(max),
	@EncryptionKey nvarchar(max),
	@ReadWriteFileGroups nvarchar(max),
	@OverrideBackupPreference nvarchar(max),
	@NoRecovery nvarchar(max),
	@URL nvarchar(max),
	@Credential nvarchar(max),
	@MirrorDirectory nvarchar(max),
	@MirrorCleanupTime int,
	@MirrorCleanupMode nvarchar(max),
	@MirrorURL nvarchar(max),
	@AvailabilityGroups nvarchar(max),
	@Updateability nvarchar(max),
	@AdaptiveCompression nvarchar(max),
	@ModificationLevel INT,
	@LogSizeSinceLastLogBackup INT,
	@TimeSinceLastLogBackup INT,
	@DataDomainBoostHost nvarchar(max),
	@DataDomainBoostUser nvarchar(max),
	@DataDomainBoostDevicePath nvarchar(max),
	@DataDomainBoostLockboxPath nvarchar(max),
	@DirectoryStructure nvarchar(max),
	@AvailabilityGroupDirectoryStructure nvarchar(max),
	@FileName nvarchar(max),
	@AvailabilityGroupFileName nvarchar(max),
	@FileExtensionFull nvarchar(max),
	@FileExtensionDiff nvarchar(max),
	@FileExtensionLog nvarchar(max),
	@Init nvarchar(max),
	@Format nvarchar(max),
	@ObjectLevelRecoveryMap nvarchar(max),
	@ExcludeLogShippedFromLogBackup nvarchar(max),
	@StringDelimiter nvarchar(max),
	@DatabaseOrder nvarchar(max),
	@DatabasesInParallel nvarchar(max),
	@LogToTable nvarchar(max),
	@Execute nvarchar(max);

SELECT
	@Databases = [Databases],
	@Directory = Directory,
	@BackupType = BackupType,
	@Verify = Verify,
	@CleanupTime = CleanupTime,
	@CleanupMode = CleanupMode,
	@Compress = [Compress],
	@CopyOnly = CopyOnly,
	@ChangeBackupType = ChangeBackupType,
	@BackupSoftware = BackupSoftware,
	@CheckSum = [CheckSum],
	@BlockSize = [BlockSize],
	@BufferCount = [BufferCount],
	@MaxTransferSize = [MaxTransferSize],
	@NumberOfFiles = NumberOfFiles,
	@MinBackupSizeForMultipleFiles = MinBackupSizeForMultipleFiles,
	@MaxFileSize = MaxFileSize,
	@CompressionLevel = CompressionLevel,
	@Description = [Description],
	@Threads = Threads,
	@Throttle = Throttle,
	@Encrypt = Encrypt,
	@EncryptionAlgorithm = EncryptionAlgorithm,
	@ServerCertificate = ServerCertificate,
	@ServerAsymmetricKey = ServerAsymmetricKey,
	@EncryptionKey = EncryptionKey,
	@ReadWriteFileGroups = ReadWriteFileGroups,
	@OverrideBackupPreference = OverrideBackupPreference,
	@NoRecovery = [NoRecovery],
	@URL = [URL],
	@Credential = [Credential],
	@MirrorDirectory = MirrorDirectory,
	@MirrorCleanupTime = MirrorCleanupTime,
	@MirrorCleanupMode = MirrorCleanupMode,
	@MirrorULR = MirrorURL,
	@AvailabilityGroups = AvailabilityGroups,
	@Updateability = Updateability,
	@AdaptiveCompression = AdaptiveCompression,
	@ModificationLevel = ModificationLevel,
	@LogSizeSinceLastLogBackup = LogSizeSinceLastLogBackup,
	@TimeSinceLastLogBackup = TimeSinceLastLogBackup,
	@DataDomainBoostHost = DataDomainBoostHost,
	@DataDomainBoostUser = DataDomainBoostUser,
	@DataDomainBoostDevicePath = DataDomainBoostDevicePath,
	@DataDomainBoostLockboxPath = DataDomainBoostLockboxPath,
	@DirectoryStructure = DirectoryStructure,
	@AvailabilityGroupDirectoryStructure = AvailabilityGroupDirectoryStructure,
	@FileName = [FileName],
	@AvailabilityGroupFileName = AvailabilityGroupFileName,
	@FileExtensionFull = FileExtensionFull,
	@FileExtensionDiff = FileExtensionDiff,
	@FileExtensionLog = FileExtensionLog,
	@Init = [Init],
	@Format = [Format],
	@ObjectLevelRecoveryMap = ObjectLevelRecoveryMap,
	@ExcludeLogShippedFromLogBackup = ExcludeLogShippedFromLogBackup,
	@StringDelimiter = StringDelimiter,
	@DatabaseOrder = DatabaseOrder,
	@DatabasesInParallel = DatabasesInParallel,
	@LogToTable = LogToTable,
	@Execute = [Execute]
FROM dbo.DatabaseBackupConfig
WHERE [Databases] ='SYSTEM_DATABASES'
	AND BackupType = 'FULL'

EXECUTE dbo.DatabaseBackup 
	@Databases = @Databases,
	@Directory = @Directory,
	@BackupType = @BackupType,
	@Verify = @Verify,
	@CleanupTime = @CleanupTime,
	@CleanupMode = @CleanupMode,
	@Compress = @Compress,
	@CopyOnly = @CopyOnly,
	@ChangeBackupType = @ChangeBackupType,
	@BackupSoftware = @BackupSoftware,
	@CheckSum = @CheckSum,
	@BlockSize = @BlockSize,
	@BufferCount = @BufferCount,
	@MaxTransferSize = @MaxTransferSize,
	@NumberOfFiles = @NumberOfFiles,
	@MinBackupSizeForMultipleFiles = @MinBackupSizeForMultipleFiles,
	@MaxFileSize = @MaxFileSize,
	@CompressionLevel = @CompressionLevel,
	@Description = @Description,
	@Threads = @Threads,
	@Throttle = @Throttle,
	@Encrypt = @Encrypt,
	@EncryptionAlgorithm = @EncryptionAlgorithm,
	@ServerCertificate = @ServerCertificate,
	@ServerAsymmetricKey = @ServerAsymmetricKey,
	@EncryptionKey = @EncryptionKey,
	@ReadWriteFileGroups = @ReadWriteFileGroups,
	@OverrideBackupPreference = @OverrideBackupPreference,
	@NoRecovery = @NoRecovery,
	@URL = @URL,
	@Credential = @Credential,
	@MirrorDirectory = @MirrorDirectory,
	@MirrorCleanupTime = @MirrorCleanupTime,
	@MirrorCleanupMode = @MirrorCleanupMode,
	@MirrorURL = @MirrorURL,
	@AvailabilityGroups = @AvailabilityGroups,
	@Updateability = @Updateability,
	@AdaptiveCompression = @AdaptiveCompression,
	@ModificationLevel = @ModificationLevel,
	@LogSizeSinceLastLogBackup = @LogSizeSinceLastLogBackup,
	@TimeSinceLastLogBackup = @TimeSinceLastLogBackup,
	@DataDomainBoostHost = @DataDomainBoostHost,
	@DataDomainBoostUser = @DataDomainBoostUser,
	@DataDomainBoostDevicePath = @DataDomainBoostDevicePath,
	@DataDomainBoostLockboxPath = @DataDomainBoostLockboxPath,
	@DirectoryStructure = @DirectoryStructure,
	@AvailabilityGroupDirectoryStructure = @AvailabilityGroupDirectoryStructure,
	@FileName = @FileName,
	@AvailabilityGroupFileName = @AvailabilityGroupFileName,
	@FileExtensionFull = @FileExtensionFull,
	@FileExtensionDiff = @FileExtensionDiff,
	@FileExtensionLog = @FileExtensionLog,
	@Init = @Init,
	@Format = @Format,
	@ObjectLevelRecoveryMap = @ObjectLevelRecoveryMap,
	@ExcludeLogShippedFromLogBackup = @ExcludeLogShippedFromLogBackup,
	@StringDelimiter = @StringDelimiter,
	@DatabaseOrder = @DatabaseOrder,
	@DatabasesInParallel = @DatabasesInParallel,
	@LogToTable = @LogToTable,
	@Execute = @Execute;
