CREATE TABLE dbo.DatabaseBackupConfig
(
[Databases] nvarchar(max) NOT NULL,
Directory nvarchar(max) NOT NULL,
BackupType nvarchar(max) NOT NULL,
Verify nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_Verify DEFAULT 'N',
CleanupTime int NULL,
CleanupMode nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_CleanupMode DEFAULT 'AFTER_BACKUP',
[Compress] nvarchar(max) NULL,
CopyOnly nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_CopyOnly DEFAULT 'N',
ChangeBackupType nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_ChangeBackupType DEFAULT 'N',
BackupSoftware nvarchar(max) NULL,
[CheckSum] nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_CheckSum DEFAULT 'N',
[BlockSize] int NULL,
[BufferCount] int NULL,
[MaxTransferSize] int NULL,
NumberOfFiles int NULL,
MinBackupSizeForMultipleFiles int NULL,
MaxFileSize int NULL,
CompressionLevel int NULL,
[Description] nvarchar(max) NULL,
Threads int NULL,
Throttle int NULL,
Encrypt char(1) NOT NULL CONSTRAINT DF_DatabaseBackup_Encrypt DEFAULT 'N',
EncryptionAlgorithm nvarchar(max) NULL,
ServerCertificate nvarchar(max) NULL,
ServerAsymmetricKey nvarchar(max) NULL,
EncryptionKey nvarchar(max) NULL,
ReadWriteFileGroups nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_ReadWriteFileGroups DEFAULT 'N',
OverrideBackupPreference nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_OverrideBackupPreference DEFAULT 'N',
[NoRecovery] nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_NoRecovery DEFAULT 'N',
[URL] nvarchar(max) NULL,
[Credential] nvarchar(max) NULL,
MirrorDirectory nvarchar(max) NULL,
MirrorCleanupTime int NULL,
MirrorCleanupMode nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_MirrorCleanupMode DEFAULT 'AFTER_BACKUP',
AvailabilityGroups nvarchar(max) NULL,
Updateability nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_Updateability DEFAULT 'ALL',
AdaptiveCompression nvarchar(max) NULL,
ModificationLevel INT NULL,
LogSizeSinceLastLogBackup INT NULL,
TimeSinceLastLogBackup INT NULL,
DataDomainBoostHost nvarchar(max) NULL,
DataDomainBoostUser nvarchar(max) NULL,
DataDomainBoostDevicePath nvarchar(max) NULL,
DataDomainBoostLockboxPath nvarchar(max) NULL,
DirectoryStructure nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_DirectoryStructure DEFAULT '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}',
AvailabilityGroupDirectoryStructure nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_AvailabilityGroupDirectoryStructure DEFAULT '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}',
[FileName] nvarchar(max) CONSTRAINT DF_DatabaseBackup_FileName NOT NULL DEFAULT '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
AvailabilityGroupFileName nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_AvailabilityGroupFileName DEFAULT '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
FileExtensionFull nvarchar(max) NULL,
FileExtensionDiff nvarchar(max) NULL,
FileExtensionLog nvarchar(max) NULL,
[Init] nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_Init DEFAULT 'N',
[Format] nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_Format DEFAULT 'N',
ObjectLevelRecoveryMap nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_ObjectLevelRecoveryMap DEFAULT 'N',
ExcludeLogShippedFromLogBackup nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_ExcludeLogShippedFromLogBackup DEFAULT 'Y',
StringDelimiter nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_StringDelimiter DEFAULT ',',
DatabaseOrder nvarchar(max) NULL,
DatabasesInParallel nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_DatabasesInParallel DEFAULT 'N',
LogToTable nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_LogToTable DEFAULT 'N',
[Execute] nvarchar(max) NOT NULL CONSTRAINT DF_DatabaseBackup_Execute DEFAULT 'Y',
);
